name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.20.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.0

      - run: yarn install

      - run: yarn test
        env:
          CI: true

      - run: yarn test:playwright
        env:
          CI: true